site_name: Maana, Inc.
pages:
    - Guides to Q: README.md
    - Analyst Guide: analyst/index.md
    - Developer Guide: developer/index.md
    - Scientist: scientist/index.md
    - Administrator: administrator/index.md
    
# theme: readthedocs